const $=id=>document.getElementById(id);
const api={async get(path){const r=await fetch(path,{headers:{Accept:"application/json"}});if(!r.ok)throw new Error(await r.text());return r.json()},async post(path,body,headers={}){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}};
const state={runs:[],agents:[],workspace:null,theme:localStorage.getItem("nexus-theme")||"dark",runFilter:""};let deferredInstallPrompt=null;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function toast(message,type="ok"){const el=document.createElement("div");el.className="toast "+type;el.textContent=message;$("toast-stack").appendChild(el);setTimeout(()=>el.remove(),3200)}
function setTheme(){document.documentElement.classList.toggle("light",state.theme==="light");$("theme-label").textContent=state.theme==="light"?"Light":"Dark";$("theme-btn").setAttribute("aria-label","Switch to "+(state.theme==="light"?"dark":"light")+" appearance");localStorage.setItem("nexus-theme",state.theme)}
function setStatusPill(id,label,tone="ok"){const el=$(id);if(!el)return;el.textContent=label;el.classList.remove("status-warning","status-danger","status-neutral");if(tone==="warning")el.classList.add("status-warning");if(tone==="danger")el.classList.add("status-danger");if(tone==="neutral")el.classList.add("status-neutral")}
function activateView(id){const target=$(id)||$("overview");document.querySelectorAll(".view-section").forEach(x=>x.classList.toggle("active",x===target));document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===target.id));$("page-title").textContent=target.id==="control-center"?"Control center":target.id.charAt(0).toUpperCase()+target.id.slice(1);history.replaceState(null,"","#"+target.id);closeMobile()}
function route(){activateView(location.hash.slice(1)||"overview")}
function closeMobile(){$("sidebar").classList.remove("open");$("mobile-scrim").classList.remove("open")}
function openMobile(){$("sidebar").classList.add("open");$("mobile-scrim").classList.add("open")}
async function loadProduct(){try{const [profile,usage,templates]=await Promise.all([api.get("/api/v1/product/profile"),api.get("/api/v1/product/usage"),api.get("/api/v1/product/templates")]);$("template-grid").innerHTML=templates.map(t=>'<div class="template-card"><h4>'+esc(t.name)+'</h4><p>'+esc(t.description)+'</p><button data-template="'+esc(t.template_id)+'">Use workflow</button></div>').join("");document.querySelectorAll("[data-template]").forEach(b=>b.onclick=async()=>{const t=await api.get("/api/v1/product/templates/"+encodeURIComponent(b.dataset.template));$("task-input").value=t.objective;activateView("overview");$("task-input").focus()})}catch(e){$("template-grid").innerHTML='<div class="empty">Workflow catalog unavailable.</div>'}}
async function loadIntelligence(){try{const [models,caps]=await Promise.all([api.get("/api/v1/models"),api.get("/api/v1/tools/capabilities")]);$("model-grid").innerHTML=models.map(m=>'<div class="model-card"><strong>'+esc(m.model_id)+'</strong><small>'+esc(m.provider)+' · '+esc(m.tier)+' · '+(m.health.available?"ready":"degraded")+'</small></div>').join("");$("capability-list").innerHTML=caps.capabilities.map(c=>'<span class="capability">'+esc(c)+'</span>').join("");$("model-count").textContent=models.filter(m=>m.health.available).length+" / "+models.length}catch(e){$("model-grid").innerHTML='<div class="empty">Model catalog unavailable.</div>'}}
async function loadAgents(){try{const data=await api.get("/api/v1/agents");state.agents=data.agents||data.items||[];$("agent-count-badge").textContent=state.agents.length+" AGENTS";$("agent-grid").innerHTML=state.agents.map(a=>'<article class="agent-card"><div class="agent-top"><b>'+esc(a.role||a.agent_id||"Agent")+'</b><i class="agent-dot"></i></div><p>'+esc(a.description||a.capabilities?.join(" · ")||"Specialist agent available to the collaboration runtime.")+'</p></article>').join("")||'<div class="empty">No agents exposed.</div>'}catch(e){$("agent-grid").innerHTML='<div class="empty">Agent catalog unavailable.</div>'}}
async function loadWorkspaces(){try{const ws=await api.get("/api/v1/workspaces"),select=$("workspace-select"),current=select.value;select.innerHTML='<option value="">No workspace selected</option>'+ws.map(w=>'<option value="'+esc(w.workspace_id)+'">'+esc(w.name)+'</option>').join("");select.value=ws.some(w=>w.workspace_id===current)?current:(ws[0]?.workspace_id||"");state.workspace=select.value||null;await loadWorkspaceData()}catch(e){$("workspace-status").textContent="Workspace service unavailable."}}
async function createWorkspace(){const name=prompt("Workspace name","My NEXUS workspace");if(!name?.trim())return;try{await api.post("/api/v1/workspaces",{name:name.trim()});await loadWorkspaces();toast("Workspace created")}catch(e){toast("Could not create workspace","error")}}
async function loadFiles(){const id=state.workspace;if(!id){$("file-list").innerHTML='<div class="empty">Create or select a workspace first.</div>';return}try{const files=await api.get("/api/v1/workspaces/"+id+"/files");$("file-list").innerHTML=files.length?files.map(f=>'<div class="file-item"><span>'+esc(f.filename)+'</span><span class="file-size">'+f.size_bytes+' bytes</span></div>').join(""):'<div class="empty">No files in this workspace.</div>';$("workspace-status").textContent=files.length+" file(s) available as context."}catch(e){$("workspace-status").textContent="Could not load files."}}
async function loadMemories(){const id=state.workspace;if(!id){$("memory-list").innerHTML='<div class="empty">Select a workspace to view memory.</div>';return}try{const memories=await api.get("/api/v1/workspaces/"+id+"/memories");$("memory-list").innerHTML=memories.slice().reverse().slice(0,10).map(m=>'<div class="memory-item">'+esc(m.content)+'<small>'+esc(m.memory_kind)+' · importance '+m.importance+'</small></div>').join("")||'<div class="empty">No memories yet.</div>'}catch(e){$("memory-list").innerHTML='<div class="empty">Memory unavailable.</div>'}}
async function loadWorkspaceData(){await Promise.all([loadFiles(),loadMemories()]);const id=state.workspace;$("knowledge-summary").textContent=id?"Workspace "+id.slice(0,12)+" · live context":"No workspace selected";$("knowledge-detail").innerHTML=id?'<div class="file-item"><span>Active workspace</span><span class="file-size">'+esc(id)+'</span></div>':'<div class="empty">Select a workspace to inspect its context.</div>'}
async function saveMemory(){const id=state.workspace,c=$("memory-input").value.trim();if(!id||!c){toast("Select a workspace and enter a memory","error");return}try{await api.post("/api/v1/memories",{workspace_id:id,content:c,memory_kind:"fact",source:"frontend"});$("memory-input").value="";await loadMemories();toast("Memory saved")}catch(e){toast("Could not save memory","error")}}
async function recallMemory(){const id=state.workspace,q=$("memory-query").value.trim();if(!id||!q){toast("Select a workspace and enter a query","error");return}try{const r=await api.post("/api/v1/workspaces/"+id+"/memories/recall",{query:q,top_k:5});$("memory-list").innerHTML=r.matches.map(m=>'<div class="memory-item">'+esc(m.content)+'<small>relevance '+Number(m.relevance).toFixed(3)+' · confidence '+Number(m.confidence).toFixed(3)+'</small></div>').join("")||'<div class="empty">No matching memory.</div>'}catch(e){toast("Recall failed","error")}}
async function uploadFile(){const id=state.workspace,file=$("file-input").files[0];if(!id||!file)return;$("workspace-status").textContent="Uploading "+file.name+"…";const data=new FormData();data.append("file",file);try{const r=await fetch("/api/v1/workspaces/"+id+"/files",{method:"POST",body:data});if(!r.ok)throw new Error(await r.text());$("file-input").value="";await loadFiles();toast("File uploaded")}catch(e){$("workspace-status").textContent="Upload failed.";toast("Upload failed","error")}}
function renderRuns(runs){state.runs=runs||[];const list=$("runs-list");const filtered=state.runs.filter(r=>(r.objective||"").toLowerCase().includes(state.runFilter.toLowerCase())||(r.status||"").toLowerCase().includes(state.runFilter.toLowerCase()));if(!filtered.length){list.innerHTML=state.runs.length?'<div class="empty">No executions match that filter.</div>':'<div class="empty">No executions yet. Give NEXUS its first goal.</div>';return}list.innerHTML=filtered.slice().reverse().slice(0,12).map(r=>'<div class="run-row"><div class="run-objective">'+esc(r.objective||"Untitled task")+'</div><div class="run-state">'+esc(r.status)+'</div><div class="run-id">'+esc((r.run_id||"").slice(0,10))+'</div></div>').join("")}
async function loadHealth(){try{const [health,models,runs]=await Promise.all([api.get("/api/v1/production/health"),api.get("/api/v1/models"),api.get("/api/v1/runs")]);$("connection-status").textContent="Operational";$("sidebar-health").textContent="Operational";$("sidebar-health-dot").style.background="var(--accent-2)";$("active-runs").textContent=health.runs.active;$("completed-runs").textContent=health.runs.completed;$("failed-runs").textContent=health.runs.failed;$("capacity").textContent=health.runtime.capacity_available+" capacity available";$("model-count").textContent=models.filter(m=>m.health.available).length+" / "+models.length;$("last-sync").textContent="Updated "+new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});renderRuns(runs)}catch(e){$("connection-status").textContent="Offline";$("sidebar-health").textContent="Offline";$("sidebar-health-dot").style.background="var(--danger)";setStatusPill("control-status","Unavailable","danger");$("last-sync").textContent="Runtime unavailable"}}
async function loadControlCenter(){try{const d=await api.get("/api/v1/control-center/summary"),healthy=d.overall_status==="healthy";setStatusPill("control-status",healthy?"Healthy":"Degraded",healthy?"ok":"warning");$("control-headline").textContent=healthy?"NEXUS systems nominal":"Attention required";$("control-summary").textContent=healthy?"All exposed operational surfaces are reporting within the production contract.":"One or more operational surfaces need review.";$("control-run-count").textContent=d.runs.active;$("control-run-detail").textContent=d.runs.total+" total · "+d.runs.failed+" failed";$("control-agent-count").textContent=d.agents.count;$("control-agent-detail").textContent=d.agents.items.map(a=>a.role).join(" · ")||"No agents";$("control-model-count").textContent=d.models.available+" / "+d.models.count;$("control-model-detail").textContent="available";$("control-tool-count").textContent=d.tools.count;$("control-tool-detail").textContent=d.tools.items.filter(t=>t.health.healthy).length+" healthy";$("control-deployment").innerHTML="<strong>"+esc(d.deployment.mode.toUpperCase())+"</strong><span>"+esc(d.deployment.region||"local")+" · "+esc(d.deployment.instance_id||"single-instance")+"</span><small>"+(d.deployment.ready?"Scale contract ready":"Scale contract blocked")+"</small>";$("control-audit").innerHTML="<strong>"+(d.audit.valid?"Verified":"Integrity issue")+"</strong><span>"+d.audit.event_count+" events · head "+d.audit.head_sequence+"</span><small>"+esc(d.audit.error||"Hash chain valid")+"</small>";$("control-timeline").innerHTML=d.runs.recent.length?d.runs.recent.slice(0,8).map(r=>'<div class="timeline-row"><span class="timeline-dot"></span><div><strong>'+esc(r.objective||r.run_id)+'</strong><small>'+esc(r.status)+' · '+(r.steps_completed||0)+' steps · '+(r.tool_calls||0)+' tools</small></div></div>').join(""):'<div class="empty">No execution history yet.</div>';$("control-sync").textContent=new Date().toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"})}catch(e){setStatusPill("control-status","Unavailable","danger");$("control-summary").textContent="Control center could not be reached."}}
async function execute(){const objective=$("task-input").value.trim();if(!objective){$("task-error").textContent="Tell NEXUS what outcome you want.";return}const btn=$("execute-btn");btn.disabled=true;$("task-error").textContent="";btn.querySelector("span").textContent="Executing…";try{const r=await api.post("/api/v1/production/tasks/execute",{objective,context:$("context-input").value.trim()||null,risk_level:$("risk-input").value,workspace_id:state.workspace},{"Idempotency-Key":crypto.randomUUID()});$("result-panel").hidden=false;$("result-output").textContent=r.output||"NEXUS completed the run without textual output.";$("verification-pill").textContent=r.verification_passed?"✓ Verified":"Needs review";$("result-meta").textContent="Run "+r.run_id+" · "+r.model+" · "+r.tool_calls+" tool calls · grounding "+r.grounding_score;activateView("runs");await Promise.all([loadHealth(),loadControlCenter()]);toast(r.verification_passed?"Run verified":"Run completed — review result",r.verification_passed?"ok":"error")}catch(e){$("task-error").textContent="Execution failed. "+e.message;toast("Execution failed","error")}finally{btn.disabled=false;btn.querySelector("span").textContent="Run with NEXUS"}}
const commands=[["Overview","overview"],["Workspace","workspace"],["Agent center","agents"],["Agent workspace","agent-workspace"],["Execution center","runs"],["Knowledge","knowledge"],["Control center","control-center"]];
function openCommand(){const modal=$("command-modal");modal.hidden=false;$("command-input").value="";renderCommands("");$("command-input").focus()}
function closeCommand(){ $("command-modal").hidden=true}
function renderCommands(q){const needle=q.toLowerCase();const items=commands.filter(x=>x[0].toLowerCase().includes(needle));$("command-results").innerHTML=items.map((x,i)=>'<div class="command-option '+(i===0?"selected":"")+'" data-command="'+x[1]+'"><span>'+x[0]+'</span><small>Go to surface</small></div>').join("")||'<div class="empty">No matching surface.</div>';document.querySelectorAll("[data-command]").forEach(x=>x.onclick=()=>{activateView(x.dataset.command);closeCommand()})}
$("theme-btn").onclick=()=>{state.theme=state.theme==="dark"?"light":"dark";setTheme()};$("command-btn").onclick=openCommand;$("command-top-btn").onclick=openCommand;$("command-modal").onclick=e=>{if(e.target.id==="command-modal")closeCommand()};$("command-input").oninput=e=>renderCommands(e.target.value);$("mobile-menu").onclick=openMobile;$("mobile-close").onclick=closeMobile;$("mobile-scrim").onclick=closeMobile;$("new-workspace-btn").onclick=createWorkspace;$("workspace-select").onchange=async e=>{state.workspace=e.target.value||null;await loadWorkspaceData()};$("file-input").onchange=uploadFile;$("save-memory-btn").onclick=saveMemory;$("recall-btn").onclick=recallMemory;$("execute-btn").onclick=execute;$("refresh-btn").onclick=async()=>{await Promise.all([loadHealth(),loadControlCenter(),loadAgents()]);toast("Telemetry refreshed")};$("runs-refresh").onclick=loadHealth;$("run-filter").oninput=e=>{state.runFilter=e.target.value.trim();renderRuns(state.runs)};$("copy-result-btn").onclick=async()=>{const value=$("result-output").textContent.trim();if(!value)return;try{await navigator.clipboard.writeText(value);toast("Result copied")}catch(e){toast("Copy unavailable — select the result manually","error")}};$("install-btn").onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$("install-btn").hidden=true};window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstallPrompt=e;$("install-btn").hidden=false});$("task-input").onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")execute()};document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand()}if(e.key==="Escape")closeCommand();if($("command-modal")&&!$("command-modal").hidden&&["ArrowDown","ArrowUp"].includes(e.key)){e.preventDefault();const options=[...document.querySelectorAll(".command-option")];if(!options.length)return;let i=options.findIndex(x=>x.classList.contains("selected"));i=e.key==="ArrowDown"?Math.min(options.length-1,i+1):Math.max(0,i-1);options.forEach((x,n)=>x.classList.toggle("selected",n===i));options[i].scrollIntoView({block:"nearest"})}if($("command-modal")&&!$("command-modal").hidden&&e.key==="Enter"){const selected=document.querySelector(".command-option.selected");if(selected)selected.click()}});window.addEventListener("hashchange",route);window.addEventListener("error",e=>{toast("NEXUS encountered a frontend error. Refresh to recover.","error");console.error(e.error||e.message)});window.addEventListener("unhandledrejection",e=>{toast("NEXUS encountered an unexpected frontend error.","error");console.error(e.reason)});if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("/web/sw.js").catch(()=>{}))}
setTheme();route();Promise.allSettled([loadHealth(),loadControlCenter(),loadAgents(),loadWorkspaces(),loadIntelligence(),loadProduct()]).finally(()=>{const boot=$("boot-screen");if(boot)boot.classList.add("is-ready")});setInterval(loadHealth,15000);setInterval(loadControlCenter,10000);
const collabState={requests:[],selectedRun:null,refreshTimer:null,eventSource:null};
const agentOptions=[["research","Researcher"],["analysis","Analyst"],["coding","Developer"],["writing","Writer"],["verification","Verifier"]];
function renderCollabRequests(){const host=$("collab-request-list");if(!host)return;host.innerHTML=collabState.requests.map((r,i)=>'<div class="collab-request"><input value="'+esc(r.objective)+'" data-collab-objective="'+i+'" placeholder="Specialist objective"><select data-collab-capability="'+i+'">'+agentOptions.map(o=>'<option value="'+o[0]+'" '+(o[0]===r.required_capability?"selected":"")+'>'+o[1]+'</option>').join("")+'</select><button class="icon-button" data-collab-remove="'+i+'" aria-label="Remove specialist">×</button></div>').join("");host.querySelectorAll("[data-collab-objective]").forEach(x=>x.oninput=e=>collabState.requests[Number(x.dataset.collabObjective)].objective=e.target.value);host.querySelectorAll("[data-collab-capability]").forEach(x=>x.onchange=e=>collabState.requests[Number(x.dataset.collabCapability)].required_capability=e.target.value);host.querySelectorAll("[data-collab-remove]").forEach(x=>x.onclick=()=>{collabState.requests.splice(Number(x.dataset.collabRemove),1);renderCollabRequests()})}
function addCollabRequest(){if(collabState.requests.length>=8){toast("Maximum of 8 workstreams","error");return}collabState.requests.push({objective:"",required_capability:"research"});renderCollabRequests()}
async function buildCollabPlan(){const objective=$("collab-objective").value.trim(),requests=collabState.requests.filter(x=>x.objective.trim()).map(x=>({...x,requester:"supervisor"}));if(!objective||!requests.length){toast("Add a goal and at least one specialist objective","error");return}const btn=$("build-collab-btn");btn.disabled=true;try{const d=await api.post("/api/v1/agents/collaborate",{objective,requests});$("collab-result").innerHTML='<div class="plan-banner"><b>Plan ready for approval</b><span>'+esc(d.workstreams.length)+' bounded workstream(s) · approval '+(d.approval_required?"required":"not required")+'</span></div>'+d.workstreams.map((w,i)=>'<div class="plan-row"><span class="plan-index">'+String(i+1).padStart(2,"0")+'</span><div><b>'+esc(w.agent_id)+'</b><small>'+esc(w.objective)+'</small></div><span class="status-pill">'+esc(w.status||"pending")+'</span></div>').join("");toast("Collaboration plan built")}catch(e){toast("Could not build collaboration plan","error");$("collab-result").innerHTML='<div class="empty">The collaboration request was rejected safely.</div>'}finally{btn.disabled=false}}
function renderRunResult(result){
  const data=result?.result||result;
  if(!data||!data.output)return false;
  $("result-panel").hidden=false;
  $("result-output").textContent=data.output;
  $("verification-pill").textContent=data.verification_passed?"✓ Verified":"Needs review";
  $("result-meta").textContent="Run "+(result.run_id||"—")+" · "+(data.model||"runtime")+" · "+(data.tool_calls||0)+" tool calls · grounding "+(data.grounding_score??"—");
  return true;
}
function renderRunSnapshot(r){
  const status=r.status||"unknown",active=["created","running"].includes(status);
  $("live-run-title").textContent=r.metadata?.objective?esc(r.metadata.objective).slice(0,72):"Run "+r.run_id.slice(0,12);
  $("live-run-subtitle").textContent=active?"Live execution · connected to runtime stream":"Execution finished";
  setStatusPill("live-run-status",status,status==="failed"||status==="cancelled"?"danger":active?"ok":status==="completed"?"ok":"neutral");
  $("cancel-run-btn").disabled=!active;$("open-run-result").disabled=!r.metadata?.result;
  const steps=Number(r.steps_completed||0),calls=Number(r.tool_calls||0),retries=Number(r.retries||0);
  const progress=active?Math.min(92,Math.max(8,steps*12)):status==="completed"||status==="failed"||status==="cancelled"?100:20;
  $("run-progress-bar").style.width=progress+"%";$("run-progress-phase").textContent=active?(steps?"Executing":"Preparing"):status;
  $("run-progress-count").textContent=steps+" steps · "+calls+" tools · "+retries+" retries";
  $("run-detail-grid").innerHTML='<div><small>Status</small><b>'+esc(status)+'</b></div><div><small>Run ID</small><b>'+esc(r.run_id)+'</b></div><div><small>Workspace</small><b>'+esc(r.metadata?.workspace_id||"—")+'</b></div><div><small>Started</small><b>'+esc(r.started_at||"—")+'</b></div><div><small>Finished</small><b>'+esc(r.finished_at||"—")+'</b></div><div><small>Duration</small><b>'+esc(r.duration_ms==null?"—":r.duration_ms+" ms")+'</b></div>';
  $("run-inspector-output").textContent=r.error?"Error: "+r.error:JSON.stringify(r.metadata?.result||r.metadata||{},null,2);
  const events=Array.isArray(r.metadata?.result?.events)?r.metadata.result.events:(Array.isArray(r.metadata?.events)?r.metadata.events:[]);
  $("run-timeline").innerHTML=(events.length?events:steps?Array.from({length:Math.min(steps,8)},(_,i)=>"step_"+(i+1)):[status]).map((e,i)=>'<div class="run-event '+(i<steps?"done":"")+'"><span></span><div><b>'+esc(String(e).replaceAll("_"," "))+'</b><small>'+((i<steps)?"Completed":active?"Current state":"Runtime state")+'</small></div></div>').join("");
  if(r.metadata?.result)renderRunResult(r.metadata);
}
async function inspectRun(runId){
  if(!runId)return;
  collabState.selectedRun=runId;
  if(collabState.eventSource){collabState.eventSource.close();collabState.eventSource=null}
  try{
    const r=await api.get("/api/v1/runs/"+encodeURIComponent(runId));
    renderRunSnapshot(r);
    if(["created","running"].includes(r.status)){
      const source=new EventSource("/api/v1/runs/"+encodeURIComponent(runId)+"/stream");
      collabState.eventSource=source;
      source.addEventListener("run",e=>{try{const next=JSON.parse(e.data);renderRunSnapshot(next);if(!["created","running"].includes(next.status)){source.close();collabState.eventSource=null;loadHealth()}}catch(err){console.error(err)}});
      source.addEventListener("error",()=>{source.close();collabState.eventSource=null;clearTimeout(collabState.refreshTimer);collabState.refreshTimer=setTimeout(()=>inspectRun(runId),3000)});
    }
  }catch(e){toast("Could not inspect run","error")}
}
function renderWorkspaceRuns(){const host=$("workspace-run-list");if(!host)return;const runs=state.runs.slice().reverse().slice(0,12);host.innerHTML=runs.length?runs.map(r=>'<button class="workspace-run-row '+(r.run_id===collabState.selectedRun?"selected":"")+'" data-inspect-run="'+esc(r.run_id)+'"><span class="run-state-dot '+esc(r.status)+'"></span><div><b>'+esc(r.objective||"Execution")+'</b><small>'+esc(r.status)+' · '+esc(r.run_id.slice(0,10))+'</small></div><span>→</span></button>').join(""):'<div class="empty">No executions yet.</div>';host.querySelectorAll("[data-inspect-run]").forEach(x=>x.onclick=()=>inspectRun(x.dataset.inspectRun))}
async function cancelSelectedRun(){if(!collabState.selectedRun)return;if(!confirm("Cancel this active NEXUS run?"))return;try{await api.post("/api/v1/runs/"+encodeURIComponent(collabState.selectedRun)+"/cancel",{});toast("Run cancellation requested");await inspectRun(collabState.selectedRun);await loadHealth()}catch(e){toast("Could not cancel run","error")}}
function initAgentWorkspace(){if(!$("agent-workspace"))return;$("add-collab-request").onclick=addCollabRequest;$("build-collab-btn").onclick=buildCollabPlan;$("cancel-run-btn").onclick=cancelSelectedRun;$("workspace-refresh").onclick=async()=>{await loadHealth();renderWorkspaceRuns();toast("Workspace refreshed")};$("open-run-result").onclick=()=>{activateView("runs");if(collabState.selectedRun)inspectRun(collabState.selectedRun)};if(!collabState.requests.length){collabState.requests=[{objective:"Gather relevant evidence",required_capability:"research"},{objective:"Verify the final result",required_capability:"verification"}];renderCollabRequests()}}
const originalRenderRuns=renderRuns;renderRuns=function(runs){originalRenderRuns(runs);renderWorkspaceRuns()};
initAgentWorkspace();
