const $=id=>document.getElementById(id);
const api={async get(path){const r=await fetch(path);if(!r.ok)throw new Error(await r.text());return r.json()},async post(path,body,headers={}){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});if(!r.ok)throw new Error(await r.text());return r.json()}};
async function loadIntelligence(){try{const [models,caps]=await Promise.all([api.get("/api/v1/models"),api.get("/api/v1/tools/capabilities")]);$("model-grid").innerHTML=models.map(m=>'<div class="model-card"><strong>'+escapeHtml(m.model_id)+'</strong><small>'+escapeHtml(m.provider)+' · '+escapeHtml(m.tier)+' · '+(m.health.available?"ready":"degraded")+'</small></div>').join("");$("capability-list").innerHTML=caps.capabilities.map(c=>'<span class="capability">'+escapeHtml(c)+'</span>').join("")}catch(e){$("model-grid").innerHTML='<div class="empty">Intelligence catalog unavailable.</div>'}}
async function loadMemories(){const id=$("workspace-select").value;if(!id){$("memory-list").innerHTML='<div class="empty">Select a workspace to view memory.</div>';return}try{const memories=await api.get("/api/v1/workspaces/"+id+"/memories");$("memory-list").innerHTML=memories.slice().reverse().slice(0,8).map(m=>'<div class="memory-item">'+escapeHtml(m.content)+'<small>'+escapeHtml(m.memory_kind)+' · importance '+m.importance+'</small></div>').join("")||'<div class="empty">No memories yet.</div>'}catch(e){$("memory-list").innerHTML='<div class="empty">Memory unavailable.</div>'}}
async function saveMemory(){const id=$("workspace-select").value;const content=$("memory-input").value.trim();if(!id||!content)return;try{await api.post("/api/v1/memories",{workspace_id:id,content,memory_kind:"fact",source:"frontend"});$("memory-input").value="";await loadMemories()}catch(e){$("memory-list").innerHTML='<div class="empty">Could not save memory.</div>'}}
async function recallMemory(){const id=$("workspace-select").value;const query=$("memory-query").value.trim();if(!id||!query)return;try{const result=await api.post("/api/v1/workspaces/"+id+"/memories/recall",{query,top_k:5});$("memory-list").innerHTML=result.matches.map(m=>'<div class="memory-item">'+escapeHtml(m.content)+'<small>relevance '+m.relevance.toFixed(3)+' · confidence '+m.confidence.toFixed(3)+'</small></div>').join("")||'<div class="empty">No matching memory.</div>'}catch(e){$("memory-list").innerHTML='<div class="empty">Recall failed.</div>'}}
async function loadWorkspaces(){try{const workspaces=await api.get("/api/v1/workspaces");const select=$("workspace-select");const current=select.value;select.innerHTML='<option value="">No workspace selected</option>'+workspaces.map(w=>'<option value="'+escapeHtml(w.workspace_id)+'">'+escapeHtml(w.name)+'</option>').join("");if(workspaces.some(w=>w.workspace_id===current))select.value=current;else if(workspaces[0])select.value=workspaces[0].workspace_id;await loadFiles();await loadMemories()}catch(e){$("workspace-status").textContent="Workspace service unavailable."}}
async function loadFiles(){const id=$("workspace-select").value;if(!id){$("file-list").innerHTML="";return}try{const files=await api.get("/api/v1/workspaces/"+id+"/files");$("file-list").innerHTML=files.length?files.map(f=>'<div class="file-item"><span>'+escapeHtml(f.filename)+'</span><span class="file-size">'+f.size_bytes+' bytes</span></div>').join(""):'<div class="empty">No files in this workspace.</div>';$("workspace-status").textContent=files.length+" file(s) available as workspace context."}catch(e){$("workspace-status").textContent="Could not load workspace files."}}
async function createWorkspace(){const name=prompt("Workspace name","My NEXUS workspace");if(!name?.trim())return;try{await api.post("/api/v1/workspaces",{name:name.trim()});await loadWorkspaces()}catch(e){$("workspace-status").textContent="Could not create workspace."}}
async function uploadFile(){const id=$("workspace-select").value;const file=$("file-input").files[0];if(!id||!file)return;const data=new FormData();data.append("file",file);$("workspace-status").textContent="Uploading…";try{const r=await fetch("/api/v1/workspaces/"+id+"/files",{method:"POST",body:data});if(!r.ok)throw new Error(await r.text());$("file-input").value="";await loadFiles()}catch(e){$("workspace-status").textContent="Upload failed."}}
async function loadHealth(){try{const [health,models,runs]=await Promise.all([api.get("/api/v1/production/health"),api.get("/api/v1/models"),api.get("/api/v1/runs")]);$("connection-status").textContent="Connected";$("model-count").textContent=models.length;$("health-pill").textContent="Healthy";$("active-runs").textContent=health.runs.active;$("capacity").textContent=health.runtime.capacity_available;$("completed-runs").textContent=health.runs.completed;$("failed-runs").textContent=health.runs.failed;renderRuns(runs)}catch(e){$("connection-status").textContent="Offline";$("health-pill").textContent="Unavailable";console.error(e)}}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function renderRuns(runs){const list=$("runs-list");if(!runs.length){list.innerHTML='<div class="empty">No runs yet. Give NEXUS its first goal.</div>';return}list.innerHTML=runs.slice().reverse().slice(0,8).map(r=>'<div class="run-row"><div class="run-objective">'+escapeHtml(r.objective||"Untitled task")+'</div><div class="run-state">'+escapeHtml(r.status)+'</div><div class="run-id">'+escapeHtml(r.run_id.slice(0,8))+'</div></div>').join("")}
async function execute(){const objective=$("task-input").value.trim();if(!objective){$("task-error").textContent="Tell NEXUS what you want done.";return}const btn=$("execute-btn");btn.disabled=true;$("task-error").textContent="";btn.innerHTML="Executing…";try{const result=await api.post("/api/v1/production/tasks/execute",{objective,context:$("context-input").value.trim()||null,risk_level:$("risk-input").value},{"Idempotency-Key":crypto.randomUUID()});$("result-panel").hidden=false;$("result-output").textContent=result.output||"NEXUS completed the run without textual output.";$("verification-pill").textContent=result.verification_passed?"✓ Verified":"Needs review";$("result-meta").textContent="Run "+result.run_id+" · "+result.model+" · "+result.tool_calls+" tool calls · grounding "+result.grounding_score;await loadHealth()}catch(e){$("task-error").textContent="Execution failed. "+e.message}finally{btn.disabled=false;btn.innerHTML='Run with NEXUS <span>→</span>'}}
$("execute-btn").addEventListener("click",execute);$("workspace-select").addEventListener("change",()=>{loadFiles();loadMemories()});$("save-memory-btn").addEventListener("click",saveMemory);$("recall-btn").addEventListener("click",recallMemory);$("new-workspace-btn").addEventListener("click",createWorkspace);$("file-input").addEventListener("change",uploadFile);$("refresh-btn").addEventListener("click",loadHealth);$("task-input").addEventListener("keydown",e=>{if((e.metaKey||e.ctrlKey)&&e.key==="Enter")execute()});loadHealth();loadWorkspaces();loadIntelligence();setInterval(loadHealth,15000);